url: "https://ipcow.com" # Your actual domain
baseurl: ""
title: IP Cow [What is my IP Address? Free IP tools!]
author: TechGuyWithABeard&nbsp;&bull;&nbsp;a ThompsonBlack company

navbar-links:
  Blog: "blog"
  Contact: "contact"
  Services: "services"
  Tools:
    - DNS Lookup: "dns-lookup"
    - HTTP Header Analyzer: "http-header-analyzer"
    - IP Lookup: "ip-lookup"
    - Ping Test: "ping"
    - Port Scanner: "port-scanner"
    - Speedtest: "speedtest"
    - Traceroute: "traceroute"
    - Whois: "whois"

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

social-network-links:
  email: "support@ipcow.com"
#  rss: true  # remove this line if you don't want to show an RSS link at the bottom
#  facebook: deanattali
  github: MichalAFerber/ipcow
  twitter: MichalAFerber
#  patreon: DeanAttali
#  youtube: "@daattali"
#  whatsapp: 15551212
#  medium: yourname
#  reddit: yourname or r/yoursubreddit
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
  discord: "ZnsJMBQCmw"
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: Here you can see the internet IP address your device is using along with information about your computer and web browser. IP Cow also offers an Ookla Speedtest and other network resources and tools.

# Select which social network share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MyWebsite.com"

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
# edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: true

# The keywords to associate with your website, for SEO purposes
keywords: "what is my ip, ip lookup, whats my ip, whatismyip, ip address lookup, find ip, find your ip address, ipaddress, ipconfig, address, remote, remote access, whois, speedtest, speed test, vpn, admin, dns lookup, dns checker, dns, tcp, udp, port scanner, port scan, portscan, telnet, ping, traceroute, http header, lan, wan, network, router, gateway, ssl, tls, ssh, openssh, linux, ipv6, ipv4"

######################################
# --- Colours / background image --- #
######################################
# Personalize the colours in your website. Colour values can be any valid CSS colour

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
#  - "https://beautifuljekyll.com/pro/dark-mode.min.css"
  - "assets/css/main.css"

# If you have common JavaScript files that should be included in every page, list them here
site-js:
#  - "/assets/js/custom-script.js"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Output options (more information on Jekyll's site)
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

include:
  - api/dns-lookup.php
  - api/http-header-analyzer.php
  - api/info.php
  - api/ping.php
  - api/port-scanner.php
  - api/traceroute.php
  - api/whois.php
  - favicon.ico
  - .htaccess

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-target-blank

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189